# Generated by Django 5.0.6 on 2024-08-13 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='session',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
